name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        versions:
          - qt: '5.12.9'
            windows-arch: 'win64_mingw73'
          - qt: '5.15.2'
            windows-arch: 'win64_mingw81'

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      if: contains(matrix.os, 'windows')
      with:
        platform: x64

    - name: Install Qt (Windows)
      uses: jurplel/install-qt-action@v2
      if: contains(matrix.os, 'windows')
      with:
        version: '${{ matrix.versions.qt }}'
        target: 'desktop'
        modules: 'qtscript'
        arch: '${{ matrix.versions.windows-arch }}'

    - name: Install Qt (Linux, MacOS)
      uses: jurplel/install-qt-action@v2
      if: "!contains(matrix.os, 'windows')"
      with:
        version: '${{ matrix.versions.qt }}'
        target: 'desktop'
        modules: 'qtscript'


    - name: Run qmake
      run: qmake -r candle.pro

    - name: Build
      run: make install
